### PR TITLE
Work continued

### PR DESCRIPTION
**Pull request by delasource**
I continued working and implemented most APIs. There are still some missing, for which i wrote TODO-comments. I'll continue with some of them, since i need them in a current project.

What else i added/changed:

* Migrated to net 5.0
* Removed Newtonsoft.Json and RestSharp dependencies. This api client now works with the integrated stuff that dotnet brings (HttpClient and System.Text.Json) - which is of course faster and has less overhead.
* Paginated result, as the "api 3.0" uses, is working.
* Simple "Example"-Project that can be run right away

Next steps:
* This pull request may be accepted
* Implement missing APIs (as documented in code)
* Release this project as a nuget package

Note: Writing automated unit tests is difficult because a real _paid_ bexio access (token) is required and there is no "sandbox" environment as far as i know._

I create this as a draft, since i'm still working on it.

### CODE REVIEW

**Comment by ninomllr** [comment]
@genyx Thanks for this addition, we really appreciate it! Yes, one issue with Bexio API is that there is no sandbox environment. We encountered this too.

Would you be willing to set the state of the PR so that we can already merge it? We are currently working with Bexio.NET as well and think we can work on this together.

**Comment by delasource** [comment]
@ninomllr Thank you. I implemented some more sales apis yesterday (the commit is part of this PR) and will test and use them today in a real world application (shop integration). So i keep looking forward to pushing to this repo if you like ;)

**Comment by ninomllr** [comment]
@genyx great, this is awesome! Let's move this project forward together. 
 
@ntold the PR is now ready to pull. Can you please try out if and what it breaks in our application and make it work with the new version? As soon as it works, you can also do a code review and then merge it, but from a quick glance over the code it looks good to me.

**Comment by delasource** [comment]
To migrate an existing project to my changes:
* Class "BexioApi" replaces "Bexio" and the constructor parameters have switched
* All functions are made async. In order to use them in a synchronized environment, do it like `bexioApi.GetProjectsAsync().GetAwaiter().GetResult()`
* TimesheetBase and TimesheetUpdate were replaced by Timesheet and old Timesheet by TimesheetFetched (which inherits from Timesheet, similar to before)

**Comment by ninomllr** [comment]
@genyx we went through it now and also tested and adapted our solution to make it work. Thanks for contributing! 

Quick question, I would like to make a quick announcement on Linkedin that there is now a new version of Bexio.NET and also announce our second Bexio project: https://github.com/substringgmbh/tap-bexio

Would you be willing to be tagged in that post? Credit where credit is due. If you want to connect, add me here: https://www.linkedin.com/in/ninomueller/

**Pull request merged**
